### ISSUE TITLE
11_webcam_features.py error

### ISSUE THREAD

**Issue by BaderAlsabbagh** [cfgnunes/cv-lab#1]
11_webcam_features.py in line 29 of the code there is an error.

> error: (-5:Bad argument) in function 'circle'
 Overload resolution failed:
 Can't parse 'center'. Sequence item with index 0 has a wrong type
 line 29, in <module>
    cv2.circle(img, (x, y), 12, red_color, -1)

**Comment by cfgnunes** [comment]
Thanks for reporting @BaderAlsabbagh!
I've just fixed the code in the commit 66a9169e25a7c7f7bee967b9026e6bce8726fac4
